export const GICS_SECTORS: Record<string, string[]> = {
  "Energy": [
    "Oil & Gas Drilling", "Oil & Gas Equipment & Services", "Integrated Oil & Gas",
    "Oil & Gas Exploration & Production", "Oil & Gas Refining & Marketing",
    "Oil & Gas Storage & Transportation", "Coal & Consumable Fuels",
  ],
  "Materials": [
    "Commodity Chemicals", "Diversified Chemicals", "Fertilizers & Agricultural Chemicals",
    "Industrial Gases", "Specialty Chemicals", "Construction Materials",
    "Metal, Glass & Plastic Containers", "Paper & Plastic Packaging Products",
    "Aluminum", "Diversified Metals & Mining", "Copper", "Gold", "Precious Metals & Minerals",
    "Silver", "Steel", "Forest Products", "Paper Products",
  ],
  "Industrials": [
    "Aerospace & Defense", "Building Products", "Construction & Engineering",
    "Electrical Components & Equipment", "Heavy Electrical Equipment",
    "Industrial Conglomerates", "Industrial Machinery & Supplies & Components",
    "Trading Companies & Distributors", "Commercial Printing",
    "Environmental & Facilities Services", "Office Services & Supplies",
    "Diversified Support Services", "Security & Alarm Services",
    "Human Resource & Employment Services", "Research & Consulting Services",
    "Data Processing & Outsourced Services", "Air Freight & Logistics",
    "Passenger Airlines", "Marine Transportation", "Railroads",
    "Cargo Ground Transportation", "Passenger Ground Transportation",
    "Airport Services", "Highways & Railtracks", "Marine Ports & Services",
  ],
  "Consumer Discretionary": [
    "Automobile Manufacturers", "Motorcycle Manufacturers",
    "Auto Parts & Equipment", "Tires & Rubber",
    "Consumer Electronics", "Home Furnishings", "Homebuilding",
    "Household Appliances", "Housewares & Specialties",
    "Leisure Products", "Apparel, Accessories & Luxury Goods",
    "Footwear", "Textiles",
    "Casinos & Gaming", "Hotels, Resorts & Cruise Lines",
    "Leisure Facilities", "Restaurants",
    "Education Services", "Specialized Consumer Services",
    "Advertising", "Broadcasting", "Cable & Satellite",
    "Movies & Entertainment", "Interactive Home Entertainment", "Publishing",
    "Distributors", "Broadline Retail", "Specialty Stores",
    "Automotive Retail", "Computer & Electronics Retail",
    "Home Improvement Retail", "Apparel Retail", "Other Specialty Retail",
  ],
  "Consumer Staples": [
    "Agricultural Products & Services", "Packaged Foods & Meats",
    "Brewers", "Distillers & Vintners", "Soft Drinks & Non-alcoholic Beverages",
    "Drug Retail", "Food Distributors", "Food Retail",
    "Consumer Staples Merchandise Retail",
    "Household Products", "Personal Care Products", "Tobacco",
  ],
  "Health Care": [
    "Health Care Equipment", "Health Care Supplies",
    "Health Care Distributors", "Health Care Services",
    "Health Care Facilities", "Managed Health Care",
    "Health Care Technology",
    "Biotechnology", "Pharmaceuticals", "Life Sciences Tools & Services",
  ],
  "Financials": [
    "Diversified Banks", "Regional Banks",
    "Diversified Financial Services", "Multi-Sector Holdings",
    "Specialized Finance", "Commercial & Residential Mortgage Finance",
    "Transaction & Payment Processing Services",
    "Consumer Finance", "Asset Management & Custody Banks",
    "Investment Banking & Brokerage", "Diversified Capital Markets",
    "Financial Exchanges & Data",
    "Insurance Brokers", "Life & Health Insurance",
    "Multi-line Insurance", "Property & Casualty Insurance", "Reinsurance",
    "Mortgage REITs", "Diversified REITs", "Industrial REITs",
    "Hotel & Resort REITs", "Office REITs", "Health Care REITs",
    "Residential REITs", "Retail REITs", "Specialized REITs",
    "Real Estate Operating Companies", "Real Estate Development",
    "Real Estate Services",
  ],
  "Information Technology": [
    "IT Consulting & Other Services", "Internet Services & Infrastructure",
    "Application Software", "Systems Software",
    "Communications Equipment", "Technology Hardware, Storage & Peripherals",
    "Electronic Equipment & Instruments",
    "Electronic Components", "Electronic Manufacturing Services",
    "Technology Distributors",
    "Semiconductor Materials & Equipment", "Semiconductors",
  ],
  "Communication Services": [
    "Alternative Carriers", "Integrated Telecommunication Services",
    "Wireless Telecommunication Services",
    "Advertising", "Broadcasting", "Cable & Satellite",
    "Movies & Entertainment", "Interactive Home Entertainment",
    "Interactive Media & Services", "Publishing",
  ],
  "Utilities": [
    "Electric Utilities", "Gas Utilities", "Multi-Utilities",
    "Water Utilities", "Independent Power Producers & Energy Traders",
    "Renewable Electricity",
  ],
  "Real Estate": [
    "Diversified REITs", "Industrial REITs", "Hotel & Resort REITs",
    "Office REITs", "Health Care REITs", "Residential REITs",
    "Retail REITs", "Specialized REITs", "Timber REITs",
    "Real Estate Operating Companies", "Real Estate Development",
    "Real Estate Services",
  ],
};

export const GICS_SECTOR_LIST = Object.keys(GICS_SECTORS);

export const TARGET_GEOGRAPHIES = [
  "North America",
  "Europe",
  "Asia-Pacific",
  "Latin America",
  "Middle East & Africa",
  "Australia & New Zealand",
  "Global",
] as const;
